name: AgentScan

on:
  # zizmor: ignore[dangerous-triggers] - DO NOT add action/checkout in this workflow as it use pull_request_target
  pull_request_target:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to analyze"
        required: true
        type: number

jobs:
  agentscan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      actions: write
    steps:
      - name: AgentScan
        uses: MatteoGabriele/agentscan-action@f41545309db947a68e22ed2643f182e754f4d41a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
